### ISSUE TITLE
PyObjC requires macOS

### ISSUE THREAD

**Issue by marwanmusa** [straussmaximilian/ocrmac#1]
Hi @straussmaximilian 

Can this be use on win user?
I try to `pip install ocrmac`, but always failed, because the need of `PyObjC framework wrappers`.
then I try to install `PyObjC` from [this](https://github.com/ronaldoussoren/pyobjc) but 
![image](https://github.com/straussmaximilian/ocrmac/assets/101170033/f6a86a19-f34a-4933-b315-92bf446d1555)

can you help me...

**Comment by marwanmusa** [comment]
Oh I just read your README.md again.
and this is only works on mac yaa

**Comment by marwanmusa** [comment]
Hopefully it will works on windows soon.

**Comment by marwanmusa** [comment]
Is there any chance that this will works on windows os?

**Comment by straussmaximilian** [comment]
Hi, thanks for creating the issue.
This will not work on Windows OS, unfortunately, as it is using some mac internals.
