### ISSUE TITLE
Consider implementing newer Live Text API

### ISSUE THREAD

**Issue by AuroraWright** [straussmaximilian/ocrmac#13]
Starting from Ventura Apple introduced the "VisionKit" APIs, which Live Text is based on. In Sonoma they updated them to add more features like vertical text recognition for CJK languages, but left the older Vision APIs as-is. In theory they're Swift-only and thus harder to implement in Python, but there's a private (undocumented) Objective C API Apple is using in WebKit that can be implemented in PyObjC. I have an implementation in my tool here: https://github.com/AuroraWright/owocr/blob/master/owocr/ocr.py#L293-L373

**Comment by straussmaximilian** [comment]
Hi, apologies for the delay. This looks great. Can you imagine creating A PR for that?

**Comment by straussmaximilian** [comment]
Closed now with #17. 
Thanks for the suggestion @AuroraWright  and thanks for implementing @Yinwhe
