### ISSUE TITLE
 Language preference does not work at present

### ISSUE THREAD

**Issue by cauchy7203** [straussmaximilian/ocrmac#4]
For example, if I want to recognize French, the results are not correct, even when I set "language_preferences = ['fra','en']

**Comment by cauchy7203** [comment]
I figured out that the language_preferences is available, and the main issue turns that the annotation does not display Chinese.

**Comment by cauchy7203** [comment]
The correct method is to use "font = ImageFont.truetype("Arial Unicode.ttf", fontsize)" , where font should be "Arial Unicode.ttf" instead of "Arial.ttf".

**Comment by straussmaximilian** [comment]
This should be fixed now, thanks!
