### ISSUE TITLE
Method to get x/y location of OCR recognized text?

### ISSUE THREAD

**Issue by hicaicai** [straussmaximilian/ocrmac#7]
Is there a way to obtain the coordinates of text within the entire screen?

**Comment by straussmaximilian** [comment]
One can get the pixel coordinates for the respective image.
I now added functionality to get this directly with `px=True`.

Note that you might want to round the coordinates

![Screenshot 2023-12-08 at 5 40 14 PM](https://github.com/straussmaximilian/ocrmac/assets/16521288/26f0cd50-8e1b-49bd-90de-2b3ce0d1c2a6)
